# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Weather-Helm
email: nixon506e@weather-helm.com
description: >-
  Sail Fast, Live Slow, Go Blue!
baseurl: ""
url: "https://www.weather-helm.com"
logo: "/assets/images/header/logo.png"
github_username:  Nixon506E
linkedin_username: lamprkei
cash_username: nixon506e
excerpt: >-
  Mobile Developer, Outdoor Adventurer, Car Enthusiast
about: >-
  I am a Cleveland based mobile first developer with a passion for clean design. I work on everything from web to mobile and I always try to keep up with the latest new tech. I love to play around with home automation and anything I can develop to make my life easier. When I'm not sitting in front of my computer I'm out on the water sailing, working on my car, or in the woods backpacking.

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
